DROP SEQUENCE SEQ_USER;
DROP TABLE TBL_USER CASCADE CONSTRAINTS;

CREATE TABLE TBL_USER (
	USER_PNO NUMBER(10) PRIMARY KEY,
	USER_EMAIL VARCHAR2(200) UNIQUE NOT NULL,
	USER_PW VARCHAR2(20) NOT NULL,
	USER_NICK VARCHAR2(30) UNIQUE NOT NULL
);



CREATE SEQUENCE SEQ_USER;

INSERT INTO TBL_USER VALUES(seq_user.nextval, 'aa@aa.com', '1234', 'aa');
INSERT INTO TBL_USER VALUES(seq_user.nextval, 'bb@bb.com', '1234', 'bb');
INSERT INTO TBL_USER VALUES(seq_user.nextval, 'cc@cc.com', '1234', 'cc');

SELECT * FROM TBL_USER;

COMMIT